- .gitignore
- config/database.yml
- config/initializers/environment_variables.rb
added environmental variables. Kindly review 
@ThaDeveloper @victorjambo @gwako94 @gtsofa
> added environmental variables

- Gemfile
- Gemfile.lock
- config/database.yml
- config/initializers/devise.rb
- config/locales/devise.en.yml
> install devise

- config/database.yml
> fixed database.yml

- app/controllers/comments_controller.rb
- app/controllers/posts_controller.rb
- app/views/posts/show.html.erb
- config/routes.rb
- db/schema.rb
Commenting to articles via form done
> Commenting

- app/controllers/comments_controller.rb
- app/models/post.rb
- app/views/posts/show.html.erb
Added link for deleting comments from posts.
> Deleting comments done

- .gitignore
- app/models/user.rb
- app/views/layouts/application.html.erb
- config/database.yml
- config/environments/development.rb
- config/routes.rb
- db/migrate/20170805083248_devise_create_users.rb
- db/schema.rb
- test/fixtures/users.yml
- test/models/user_test.rb
> setup the USER model

- app/controllers/comments_controller.rb
- app/controllers/posts_controller.rb
- app/models/comment.rb
- app/models/post.rb
- app/models/user.rb
- app/views/posts/show.html.erb
- config/routes.rb
> implemented like and unlike

- Gemfile
- Gemfile.lock
- app/controllers/posts_controller.rb
- app/models/post.rb
- app/views/posts/_form.html.erb
- app/views/posts/index.html.erb
- app/views/posts/show.html.erb
- config/routes.rb
- db/migrate/20170805102936_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb
- db/migrate/20170805102937_add_missing_unique_indices.acts_as_taggable_on_engine.rb
- db/migrate/20170805102938_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine.rb
- db/migrate/20170805102939_add_missing_taggable_index.acts_as_taggable_on_engine.rb
- db/migrate/20170805102940_change_collation_for_tag_names.acts_as_taggable_on_engine.rb
- db/migrate/20170805102941_add_missing_indexes_on_taggings.acts_as_taggable_on_engine.rb
- db/schema.rb
> implementation of tags

- app/views/posts/show.html.erb
Only logged in user can comment
> Grab current user as the commentor

- app/controllers/comments_controller.rb
- app/models/comment.rb
- app/models/user.rb
- app/views/posts/show.html.erb
- db/migrate/20170808171913_add_user_id_to_comments.rb
- db/schema.rb
Added user_id column to comment table in that one user has many comments and a comment only has one user.
> Added relationship between comment and user

- app/controllers/posts_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/user.rb
- config/database.yml
Sorted redirection Issue.
@ThaDeveloper 
@gtsofa 
@mwenda-eric 
@victorjambo 
@eunice12jk
> Fixed redirection issue

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css.scss
- app/views/posts/_form.html.erb
- app/views/posts/edit.html.erb
used select2 Gem to add dropdown feature to select category for a post. 
Still working on selecting multiple categories for one post
> Post category dropdown select

- app/assets/javascripts/application.js
- app/assets/javascripts/cusom.js
- app/assets/javascripts/flashes.js
- app/assets/stylesheets/custom.scss
- app/controllers/comments_controller.rb
- app/controllers/posts_controller.rb
- app/models/post.rb
- app/views/posts/index.html.erb
- db/schema.rb
I have redesigned the way Articles are displayed.
> Posts UI Redesign

- app/controllers/suggestions_controller.rb
- app/views/suggestions/index.html.erb
Can now submit a suggestion without page reload. Removed the new and show actions.
> Worked on single page submit with ajax

- app/assets/javascripts/announcements.coffee
- app/assets/stylesheets/announcements.scss
- app/controllers/announcements_controller.rb
- app/helpers/announcements_helper.rb
- app/models/announcement.rb
- app/views/announcements/index.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- db/migrate/20170902151016_create_announcements.rb
- db/schema.rb
- lib/tasks/db.rake
- test/controllers/announcements_controller_test.rb
- test/fixtures/announcements.yml
- test/models/announcement_test.rb
- t|
* announcement model with one view
* made changes to `rake db:populate`
> Announcements

- Gemfile
- Gemfile.lock
- app/controllers/posts_controller.rb
- app/views/posts/index.html.erb
> Added post model pagination

- app/views/kaminari/_first_page.html.erb
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_last_page.html.erb
- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/kaminari/_prev_page.html.erb
Bootstrap styling on pagination.
> added bootstrap styling on pagination

- app/mailers/suggestion_mailer.rb
- config/environments/production.rb
Changed action mailer default url options to reflect heroku app url
> Actionmailer config

- config/application.rb
app is attempting to connect to the database as part of rake assets:precompile
> Heroku config

- app/admin/category.rb
- app/admin/post.rb
- app/admin/suggestion.rb
- app/assets/stylesheets/active_admin.scss
- app/assets/stylesheets/custom.scss
- app/controllers/home_controller.rb
- app/controllers/posts_controller.rb
- app/views/home/index.html.erb
- db/migrate/20171101100608_add_published_to_post.rb
- db/schema.rb
Admins can now publish a post. all post submitted will have published set to false by default.
> [Feature] Add publish function to posts

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy/production.rb
- config/deploy/staging.rb
- config/nginx.conf
> Capistrano

- app/controllers/polls_controller.rb
- app/views/polls/_form.html.erb
* [Use collection_select](https://apidock.com/rails/ActionView/Helpers/FormOptionsHelper/collection_select)
> Hot fix on polls
